name: Split baby-bb-001.png

on:
  workflow_dispatch:
  schedule:
    - cron: '3 4 * * *'  # 07:03 TRT، 3 دقیقه بعد از generateِ 06:00

permissions:
  contents: write

concurrency:
  group: split-sliced-queue
  cancel-in-progress: false

env:
  CATEGORY: baby
  SUBDIR: babyclothing
  CODE: bb
  STEM: bb-001
  SCRIPT: scripts/baby/bb-001s.mjs
  STAGE_GLOB: daily/baby/babyclothing/sliced/*.png
  COMMIT_MSG: Auto-split: update sliced images from bb-001.png

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Pull latest changes (pre-run)
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Install canvas system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Run splitter
        run: node "$SCRIPT"

      - name: Pull latest changes (pre-push)
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Stage sliced images only
        run: |
          git config user.name "selglo-bot"
          git config user.email "bot@selglo.com"
          git add -- ":(glob)$STAGE_GLOB"
          if git diff --cached --quiet; then
            echo "✅ No sliced images to commit"
            exit 0
          fi
          echo "🔍 Staged:"
          git diff --cached --name-only

      - name: Commit and push with retry
        run: |
          git commit -m "$COMMIT_MSG" || exit 0
          attempts=0
          until [ $attempts -ge 3 ]
          do
            if git push origin HEAD:main; then
              echo "✅ Push succeeded"
              break
            fi
            attempts=$((attempts+1))
            echo "⚠ Push failed (attempt $attempts). Rebase & retry..."
            git fetch origin main
            git pull --rebase origin main || true
          done
          if [ $attempts -ge 3 ]; then
            echo "❌ Push failed after 3 attempts. Check branch protections."
            exit 1
